params:
  train_data_path: ${hydra:runtime.cwd}\MNISTDataset\MNIST_train_data.gz
  train_labels_path: ${hydra:runtime.cwd}\MNISTDataset/MNIST_train_labels.gz
  test_data_path: ${hydra:runtime.cwd}\MNISTDataset\t10k-images-idx3-ubyte.gz
  test_labels_path: ${hydra:runtime.cwd}\MNISTDataset\t10k-labels-idx1-ubyte.gz

hyperparams:
  batch_size: 512