params:
  train_data_path: ${hydra:runtime.cwd}\MNISTDataset\MNIST_train_data.gz
  train_labels_path: ${hydra:runtime.cwd}\MNISTDataset/MNIST_train_labels.gz
  test_data_path: ${hydra:runtime.cwd}\MNISTDataset\t10k-images-idx3-ubyte.gz
  test_labels_path: ${hydra:runtime.cwd}\MNISTDataset\t10k-labels-idx1-ubyte.gz
  pretrain_model_path: ${hydra:runtime.cwd}\TrainedModels\

hyperparams:
  batch_size: 128
  epochs: 1
  learning_rate: 0.0001
  optimizer: 'ADAM'
